name: extension_dart
description: A lightweight Dart extensions that simplify framework usage for elegant, effortless app development.
homepage: https://github.com/leo1394/extension_dart
repository: https://github.com/leo1394/extension_dart
issue_tracker: https://github.com/leo1394/extension_dart/issues
version: 1.0.3

environment:
  sdk: ^3.6.1

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.24.0

topics:
  - dart-extension
  - extension
  - extensions
  - dart-extensions
  - utils
